### PR TITLE
upgrade core-foundation dep version

### PR DESCRIPTION
**Pull request by cjubb39**
I know you just cut a build yesterday.  Are you willing to cut another with just an upgrade in the dep version for `core-foundation`?  This will help me get rid of some duplicate deps in my project.

It's a clean update since core-foundation is very unlikely to have a breaking change :)

Thanks!

### CODE REVIEW

**Comment by cjubb39** [comment]
Can also update the version in the `Cargo.toml` to "*" if you'd prefer

**Comment by sfackler** [comment]
Wildcard dependencies can't be published.

This will be a breaking change, so I'm going to fold some other fixes into it.

**Comment by cjubb39** [comment]
Why is this a breaking change?  There were no code changes to either of the crates in this repo.

**Comment by sfackler** [comment]
core-foundation 0.2's types are not the same as core-foundation 0.4's types, so anyone that depends on core-foundation 0.2 and security-framework 0.1 is going to be broken if the dependency is bumped.

**Comment by jrmuizel** [comment]
core-foundation has been updated so this can be closed.

**Pull request closed without merging**
