### PR TITLE
Add a client example

### PR DESCRIPTION
**Pull request by jrmuizel**

### CODE REVIEW

**Comment by sfackler** [comment]
Could this mirror the existing example in the rustdoc: http://sfackler.github.io/rust-security-framework/doc/v0.1.10/security_framework/secure_transport/index.html#examples?

In particular, I'd like to encourage use of `ClientBuilder` rather than `SslContext` directly since that can be pretty tricky to configure.

**Comment by jrmuizel** [comment]
I'll take a look.

**Comment by jrmuizel** [comment]
I switched to ClientBuilder

**Comment by sfackler** [comment]
Thanks!

**Pull request merged**
